# -*- coding: utf-8 -*-
"""Copy of HW4_Part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeczYYHhBt7l58j7W8gG3MgwbeaTvyJc
"""

import pandas as pd
import matplotlib.pyplot as plt

"""**Q1** Please use Pandas to read olympic_medals.csv and use parallel_categories function from plotly.express to visualize proportions of medal type for each gender from since year 2000. Please see the example in the Python notebook we walked through in the class."""

#please use this cell to read and select your data
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATA-20260125T234113Z-1-001/DATA/olympic_medals.csv')

from google.colab import drive
drive.mount('/content/drive')

#Please use this cell to create your your figure. Please use Year column to color your graph.
#Filter the data
df_filtered = df[df['Year'] >= 2000]

#use the parallel_categories function
fig = px.parallel_categories(
    df_filtered,
    dimensions=['Gender', 'Medal'],
    color='Year',
    color_continuous_scale=px.colors.sequential.Viridis
)
fig.show()

"""**Q2** Please inspect the code below and observe how values are plotted by running it. Then, read the 2016elections.csv from the DATA folder and select rows for AR, MI, CA, and WI. Then, utilize stacked bar plot, to stack vote percentages for Trump, Clinton, Johnson, and Others. Please see 'pct_clinton',	'pct_trump',	'pct_johnson',	'pct_other' columns. Make sure that your x tick labels are those four states above."""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# create DataFrame
df = pd.DataFrame({'High Temp': [28, 30, 34, 38, 45, 42,
                                 38, 35, 32, 28, 25, 21],
                   'Low Temp': [22, 26, 30, 32, 41, 38,
                                32, 31, 28, 22, 15, 15],
                   'Avg Temp': [25, 28, 32, 35, 43, 40,
                                35, 33, 30, 25, 20, 18]},
                  index=['Jan', 'Feb', 'Mar', 'Apr', 'May',
                         'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
                         'Nov', 'Dec'])


# create stacked bar chart for monthly temperatures
df.plot(kind='bar', stacked=True, color=['red', 'skyblue', 'green'])

# labels for x & y axis
plt.xlabel('Months')
plt.ylabel('Temp ranges in Degree Celsius')

# title of plot
plt.title('Monthly Temperatures in a year')

#You can use this cell to write your code. It is doable at most 4 lines of code.
import pandas as pd
import matplotlib.pyplot as plt

#create dataframe
df = pd.DataFrame({
    'Trump': [60.57, 47.25, 31.49, 47.22],
    'Clinton': [33.65, 47.03, 61.48, 46.45],
    'Johnson': [2.64, 2.16, 3.36, 2.74],
    'Others': [3.13, 1.04, 3.66, 3.58]
}, index=['AR', 'MI', 'CA', 'WI'])

#create stacked bar chart
df.plot(kind='bar', stacked=True, color=['red', 'skyblue', 'green', 'orange'])

#labels for x & y axis
plt.xlabel('States')
plt.ylabel('Vote Percentages')

#title of plot
plt.title('2016 Election Results')
plt.show()